import StyleDady from "@/styles/Background_Daddy.module.css";
import Head from "next/head";

import Topo from "@/Components/Topo_Section";
import Principal from "@/Components/Principal_Section";
import Produtos from "@/Components/Products_Section";
import Sobre from "@/Components/Sobre_Section";
import Contact from "@/Components/Contato_Section";
import Footer from "@/Components/Rodape_Section";


export default function Home() {
return (
<div className={StyleDady.Container_Daddy}>
<Head>
<title>Óticas Diniz</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon_diniz.png" />
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>

</Head>

<section className={StyleDady.Main_Container}>
<header>
<Topo/>
</header>

<main>
<Principal/>
<Produtos/>
<Sobre/>
<Contact/>
</main>
<Footer/>
</section>


</div>
);
}
